name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create Release Folder
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release
    - name: Switch to Release Folder
      run: |
        ls -la
        zip -r release.zip release/
        ls -la
        pwd
        cd release
        ls -la
    - name: Bump version and push tag
      uses: Anirudhbly/github-tag-action@master
      env:
        SOURCE: /home/runner/work/ZipRepoProject/ZipRepoProject/release
        INITIAL_VERSION: 16.2.27
        GITHUB_TOKEN: ${{ secrets.ZIPTOKEN }}
        REPO_OWNER: Anirudhbly
